// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GreenleafiManager
{
	public partial class PhotoViewerViewController : UIViewController
	{
		public PhotoViewerViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
