// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using CoreGraphics;
using System.Linq;
using System.IO;
using System.Collections.Generic;
//using Cirrious.FluentLayouts.Touch;

namespace GreenleafiManager
{
	public partial class InvoicePreviewViewController : UIViewController
	//public partial class InvoicePreviewViewController : UIScrollView
	{
		//Static layout data
		nfloat initialTopMargin = DefaultDetailsLayoutSettings.InitialTopMargin;

		nfloat defaultLabelHeight = DefaultDetailsLayoutSettings.DefaultLabelHeight;

		nfloat defaultTextFieldWidth = DefaultDetailsLayoutSettings.DefaultTextFieldWidth;

		nfloat defaultHorizontalSpacing = DefaultDetailsLayoutSettings.InvoiceHorizontalSpacing;
		nfloat defaultItemVerticalSpacing = DefaultDetailsLayoutSettings.InvoiceDeatilVerticalSpacing;
		public bool IsPrint { get; set; }
		//Editable fields


		UILabel customerName, saleslabel, skuLastLabel;
		UILabel customerAddress1;
		UILabel customerAddress2;
		public Invoice objInvoice = new Invoice();
		UIScrollView scrollView;
		public InvoicePreviewViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			scrollView = new UIScrollView(this.View.Frame);
			scrollView.ContentSize = new CGSize(this.View.Frame.Width, this.View.Frame.Height + 20);
			this.View.Add(scrollView);
			SetupViewUIItems();
			if (IsPrint)
				ConvertPDFFromView();
		}
		public void SetupViewUIItems()
		{
			BuildCustomerUI(40, initialTopMargin);
			nfloat _X = View.Frame.Width / 2 + 30;
			BuildSalesUI(20, customerAddress2.Frame.Y + customerAddress2.Frame.Height + 30);
			BuildSKUsUI(20, saleslabel.Frame.Y + saleslabel.Frame.Height + 30);
			_X = View.Frame.Width - 318;
			nfloat _Y = View.Frame.Height - 5 * defaultLabelHeight - 20;
			BuildAmountUI(_X, 1 + skuLastLabel.Frame.Y + defaultLabelHeight * objInvoice.Items.Count);
			//BuildPaidUI(_X, skuLastLabel.Frame.Y + defaultLabelHeight * (objInvoice.Items.Count + 3));
		}
		private void BuildCustomerUI(nfloat initialX, nfloat initialY)
		{
			var lblOnline = new UILabel(new CGRect(initialX + 20, initialY + 20, View.Frame.Width / 2 - 100, 150));
			lblOnline.Text = "ONLINE";
			lblOnline.TextAlignment = UITextAlignment.Center;
			lblOnline.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			lblOnline.TextColor = UIColor.Black;
			lblOnline.Font = UIFont.BoldSystemFontOfSize(20);
			scrollView.AddSubview(lblOnline);

			initialX = View.Frame.Width / 2 + 40;
			var label = new UILabel(new CGRect(initialX, initialY, View.Frame.Width / 2 - 100, 40));
			label.Text = "Customer";
			label.TextAlignment = UITextAlignment.Center;
			label.BackgroundColor = UIColor.LightGray;
			label.TextColor = UIColor.Black;
			label.Layer.CornerRadius = 10;
			label.ClipsToBounds = true;
			label.Font = UIFont.BoldSystemFontOfSize(20);
			scrollView.AddSubview(label);

			customerName = new UILabel(new CGRect(initialX,
				label.Frame.Y + label.Frame.Height + defaultItemVerticalSpacing,
				defaultTextFieldWidth, defaultLabelHeight));
			customerName.Text = "Luke Bryan";
			customerName.Font = GlobalUISettings.InvoiceTextFieldFont;
			scrollView.AddSubview(customerName);

			var seprator1 = new UIView(new CGRect(initialX, customerName.Frame.Y + customerName.Frame.Height + 2, defaultTextFieldWidth, 1));
			seprator1.BackgroundColor = UIColor.Gray;
			scrollView.AddSubview(seprator1);
			customerAddress1 = new UILabel(new CGRect(initialX,
				customerName.Frame.Y + defaultLabelHeight + defaultItemVerticalSpacing,
				defaultTextFieldWidth, defaultLabelHeight));
			customerAddress1.Text = "12 Andrez Sperks";
			customerAddress1.Font = GlobalUISettings.InvoiceTextFieldFont;
			scrollView.AddSubview(customerAddress1);

			var seprator2 = new UIView(new CGRect(initialX, customerAddress1.Frame.Y + customerAddress1.Frame.Height + 2, defaultTextFieldWidth, 1));
			seprator2.BackgroundColor = UIColor.Gray;
			scrollView.AddSubview(seprator2);

			customerAddress2 = new UILabel(new CGRect(initialX,
				customerAddress1.Frame.Y + defaultLabelHeight + defaultItemVerticalSpacing,
				defaultTextFieldWidth, defaultLabelHeight));
			customerAddress2.Text = "Los Angles CA";
			customerAddress2.Font = GlobalUISettings.InvoiceTextFieldFont;
			scrollView.AddSubview(customerAddress2);

			var lblZip = new UILabel(new CGRect(customerAddress2.Frame.X + customerAddress2.Frame.Width + defaultHorizontalSpacing,
				customerAddress1.Frame.Y + defaultLabelHeight + defaultItemVerticalSpacing,
				100, defaultLabelHeight));
			lblZip.Text = "79856";
			lblZip.ToGreenLeafLabel();
			scrollView.AddSubview(lblZip);

			var seprator3 = new UIView(new CGRect(initialX, customerAddress2.Frame.Y + customerAddress2.Frame.Height + 2, defaultTextFieldWidth, 1));
			seprator3.BackgroundColor = UIColor.Gray;
			scrollView.AddSubview(seprator3);

			#region SetValues

			if (objInvoice != null && objInvoice.Customer != null)
			{
				lblOnline.Lines = 4;
				//lblOnline.Text = objInvoice.Location?.Name + "\n";
				lblOnline.Text = objInvoice.Location?.Address1 + "\n";
				lblOnline.Text = lblOnline.Text + objInvoice.Location?.Address2 + "\n";
				lblOnline.Text = lblOnline.Text + objInvoice.Location?.City + ", " + objInvoice.Location?.Province + "\n";
				lblOnline.Text = lblOnline.Text + objInvoice.Location?.Zip;

				customerName.Text = objInvoice.Customer?.FullName;
				customerAddress1.Text = objInvoice.Customer?.Address;
				customerAddress2.Text = objInvoice.Customer?.City + " " + objInvoice.Customer?.Country;
				lblZip.Text = objInvoice.Customer?.Zip;
			}
			#endregion
		}

		private void BuildSalesUI(nfloat initialX, nfloat initialY)
		{
			nfloat fullWidth = View.Frame.Width - 2 * initialX;

			var label = new UILabel(new CGRect(initialX, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "Sales Person"
			};
			label.ToGreenLeafLabel();
			label.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			scrollView.Add(label);

			var label2 = new UILabel(new CGRect(label.Frame.X + label.Frame.Width - 1, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "Date"
			};
			label2.ToGreenLeafLabel();

			label2.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			scrollView.Add(label2);

			var label3 = new UILabel(new CGRect(label2.Frame.X + label2.Frame.Width - 1, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "Location"
			};
			label3.ToGreenLeafLabel();

			label3.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			scrollView.Add(label3);

			var label4 = new UILabel(new CGRect(label3.Frame.X + label3.Frame.Width - 1, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "Reciept #"
			};
			label4.ToGreenLeafLabel();

			label4.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			scrollView.Add(label4);

			var label5 = new UILabel(new CGRect(label4.Frame.X + label4.Frame.Width - 1, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "Customer #"
			};
			label5.ToGreenLeafLabel();

			label5.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			scrollView.Add(label5);

			var label6 = new UILabel(new CGRect(label5.Frame.X + label5.Frame.Width - 1, initialY, fullWidth / 6 + 6, defaultLabelHeight))
			{
				Text = "Paid By"
			};
			label6.ToGreenLeafLabel();
			label6.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			scrollView.Add(label6);

			initialY = initialY + defaultLabelHeight - 1;
			saleslabel = new UILabel(new CGRect(initialX, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "Paul marks",
				BackgroundColor = UIColor.LightGray
			};
			saleslabel.ToGreenLeafLabel();
			scrollView.Add(saleslabel);

			var lblDate = new UILabel(new CGRect(saleslabel.Frame.X + saleslabel.Frame.Width - 1, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "15/08/2016",
				BackgroundColor = UIColor.LightGray
			};
			lblDate.ToGreenLeafLabel();
			scrollView.Add(lblDate);

			var lblLoc = new UILabel(new CGRect(lblDate.Frame.X + lblDate.Frame.Width - 1, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "MAUI",
				BackgroundColor = UIColor.LightGray
			};
			lblLoc.ToGreenLeafLabel();
			scrollView.Add(lblLoc);

			var lblReceipt = new UILabel(new CGRect(lblLoc.Frame.X + lblLoc.Frame.Width - 1, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "6565",
				BackgroundColor = UIColor.LightGray
			};
			lblReceipt.ToGreenLeafLabel();
			scrollView.Add(lblReceipt);

			var lblCustomer = new UILabel(new CGRect(lblReceipt.Frame.X + lblReceipt.Frame.Width - 1, initialY, fullWidth / 6, defaultLabelHeight))
			{
				Text = "65656",
				BackgroundColor = UIColor.LightGray
			};
			lblCustomer.ToGreenLeafLabel();
			scrollView.Add(lblCustomer);

			var lblRaid = new UILabel(new CGRect(lblCustomer.Frame.X + lblCustomer.Frame.Width - 1, initialY, fullWidth / 6 + 6, defaultLabelHeight))
			{
				Text = "V $",
				BackgroundColor = UIColor.LightGray
			};
			lblRaid.ToGreenLeafLabel();
			scrollView.Add(lblRaid);

			#region SetValues
			if (objInvoice != null)
			{
				//if (objInvoice.Location != null)
				lblLoc.Text = objInvoice.Location?.Name;
				if (objInvoice.Customer != null)
					lblCustomer.Text = objInvoice.Customer?.FullName;
				lblDate.Text = objInvoice.Date;
				lblReceipt.Text = objInvoice.Number;
				//lblRaid.Text = $"${objInvoice.PaidAmount.ToString("F")}";
				lblRaid.Text = PaymentPaiedByLogic.Calculate(objInvoice?.Payments.ToList());
				saleslabel.Text = objInvoice.User?.FullName;
			}

			#endregion
		}

		private void BuildSKUsUI(nfloat initialX, nfloat initialY)
		{
			nfloat fullWidth = View.Frame.Width - 2 * initialX;

			var headerView = new UIView(new CGRect(initialX, initialY, fullWidth - initialX, defaultLabelHeight));

			var superView = new UIView(new CGRect(initialX, headerView.Frame.Height + headerView.Frame.Y + 1, fullWidth - initialX, 200));

			#region Headers

			nfloat hWidth = headerView.Frame.Width / 20;

			var label = new UILabel(new CGRect(0, 0, hWidth * 2, defaultLabelHeight))
			{
				Text = "SKU",
			};
			label.ToGreenLeafLabel();
			label.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			headerView.Add(label);

			var label2 = new UILabel(new CGRect(label.Frame.X + label.Frame.Width - 1, 0, hWidth * 2, defaultLabelHeight))
			{
				Text = "Style Code",
			};
			label2.ToGreenLeafLabel();
			label2.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			headerView.Add(label2);

			var label3 = new UILabel(new CGRect(label2.Frame.X + label2.Frame.Width - 1, 0, hWidth * 13, defaultLabelHeight))
			{
				Text = "Description",
			};
			label3.ToGreenLeafLabel();

			label3.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			headerView.Add(label3);

			var label4 = new UILabel(new CGRect(label3.Frame.X + label3.Frame.Width - 1, 0, hWidth * 3 + 25, defaultLabelHeight))
			{
				Text = "Amount",
			};
			label4.ToGreenLeafLabel();

			label4.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			headerView.Add(label4);

			#endregion

			scrollView.Add(headerView);
			if (objInvoice != null && objInvoice.Items != null)
			{
				nfloat y = 0;
				foreach (var item in objInvoice.Items)
				{
					var mainView = new UIView(new CGRect(0, y, fullWidth, defaultLabelHeight));
					y += defaultLabelHeight;
					initialY = initialY + defaultLabelHeight - 1;
					var lblSKU = new UILabel(new CGRect(0, 0, hWidth * 2, defaultLabelHeight))
					{
						Text = item.Sku,
						BackgroundColor = UIColor.LightGray
					};
					lblSKU.ToGreenLeafLabel();
					mainView.Add(lblSKU);



					var lblCode = new UILabel(new CGRect(lblSKU.Frame.X + lblSKU.Frame.Width - 1, 0, hWidth * 2, defaultLabelHeight))
					{
						Text = item.MetalCode,
						BackgroundColor = UIColor.LightGray
					};
					lblCode.ToGreenLeafLabel();
					mainView.Add(lblCode);


					var lblDsc = new UILabel(new CGRect(lblCode.Frame.X + lblCode.Frame.Width - 1, 0, hWidth * 13, defaultLabelHeight))
					{
						Text = item.Description,
						BackgroundColor = UIColor.LightGray
					};
					lblDsc.ToGreenLeafLabel();
					mainView.Add(lblDsc);


					var lblAmount = new UILabel(new CGRect(lblDsc.Frame.X + lblDsc.Frame.Width - 1, 0, hWidth * 3 + 25, defaultLabelHeight))
					{
						Text = item.TagPrice.ToString("C"),
						BackgroundColor = UIColor.LightGray
					};
					lblAmount.ToGreenLeafLabel();
					mainView.Add(lblAmount);

					superView.Add(mainView);
					skuLastLabel = new UILabel(mainView.Frame);
				}
				scrollView.Add(superView);
				skuLastLabel = new UILabel(superView.Frame);
			}
		}

		private void BuildAmountUI(nfloat initialX, nfloat initialY)
		{
			var view = new UIView(new CGRect(initialX - 20, initialY, 500, defaultLabelHeight * 5));

			var label = new UILabel(new CGRect(0, 0, 150, defaultLabelHeight))
			{
				Text = "Sub Total",
			};
			label.ToGreenLeafLabel();
			label.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			view.Add(label);

			var label2 = new UILabel(new CGRect(label.Frame.X + label.Frame.Width - 1, 0, 170, defaultLabelHeight))
			{
				Text = "",
			};
			label2.ToGreenLeafLabel();
			view.Add(label2);

			var label3 = new UILabel(new CGRect(0, label.Frame.Y + defaultLabelHeight - 1, 150, defaultLabelHeight))
			{
				Text = String.Format("Sales Tax - {0}%", objInvoice.IsMailOrder ? "0" : (objInvoice.LocationTax * 100).ToString())
			};
			label3.ToGreenLeafLabel();
			label3.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			view.Add(label3);

			var label4 = new UILabel(new CGRect(label3.Frame.X + label3.Frame.Width - 1, label3.Frame.Y, 170, defaultLabelHeight))
			{
				Text = String.Format("{0}", objInvoice.IsMailOrder ? "$0.00" : Math.Round(((double)(objInvoice.LocationTax * (decimal)objInvoice.TotalPrice)), 2).ToString("C"))
			};
			label4.ToGreenLeafLabel();
			view.Add(label4);

			var label5 = new UILabel(new CGRect(0, label4.Frame.Y + defaultLabelHeight - 1, 150, defaultLabelHeight))
			{
				Text = "Total Amount"
			};
			label5.ToGreenLeafLabel();
			label5.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			view.Add(label5);

			var labelPaidValue6 = new UILabel(new CGRect(label5.Frame.X + label5.Frame.Width - 1, label5.Frame.Y, 170, defaultLabelHeight))
			{
				Text = "Total Price",
			};
			labelPaidValue6.ToGreenLeafLabel();
			view.Add(labelPaidValue6);

			if (objInvoice != null)
			{
				labelPaidValue6.Text = objInvoice.TotalPrice.ToString("C");
				//if (objInvoice.OrderTotal != null)
				label2.Text = objInvoice.OrderTotal.ToString("C");
			}

			//Paid UI
			var lblTotalPaid = new UILabel(new CGRect(0, label5.Frame.Y + defaultLabelHeight - 1, 150, defaultLabelHeight))
			{
				Text = "Total Paid",
			};
			lblTotalPaid.ToGreenLeafLabel();
			lblTotalPaid.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			view.Add(lblTotalPaid);

			var lblPaidAmount = new UILabel(new CGRect(lblTotalPaid.Frame.X + lblTotalPaid.Frame.Width - 1, lblTotalPaid.Frame.Y, 170, defaultLabelHeight))
			{
				Text = ""
			};
			lblPaidAmount.ToGreenLeafLabel();
			view.Add(lblPaidAmount);

			var lblBalance = new UILabel(new CGRect(0, lblTotalPaid.Frame.Y + defaultLabelHeight - 1, 150, defaultLabelHeight))
			{
				Text = "Balance"
			};
			lblBalance.ToGreenLeafLabel();
			lblBalance.BackgroundColor = UIColor.FromRGB(210, 210, 210);
			view.Add(lblBalance);

			var lblBalanceAmount = new UILabel(new CGRect(lblBalance.Frame.X + lblBalance.Frame.Width - 1, lblBalance.Frame.Y, 170, defaultLabelHeight))
			{
				Text = "0.00",
			};
			lblBalanceAmount.ToGreenLeafLabel();
			view.Add(lblBalanceAmount);
			if (objInvoice != null)
			{
				if (objInvoice.PaidAmount != 0.00)
					lblPaidAmount.Text = Math.Round(objInvoice.PaidAmount, 2).ToString("C");
				else
					lblPaidAmount.Text = "0.00";
				if (objInvoice.BalanceDue != (double)0)
					lblBalanceAmount.Text = Math.Round(objInvoice.BalanceDue, 2).ToString("C");
				else
					lblBalanceAmount.Text = "0.00";

			}

			scrollView.Add(view);
		}


		private void BuildPaidUI(nfloat initialX, nfloat initialY)
		{

		}

		void ConvertPDFFromView()
		{
			NSMutableData pdfData = new NSMutableData();

			//UIGraphics.BeginPDFContext
			UIGraphics.BeginPDFContext(pdfData, View.Bounds, null);
			UIGraphics.BeginPDFPage();
			CGContext pdfContext = UIGraphics.GetCurrentContext();
			View.Layer.RenderInContext(pdfContext);
			UIGraphics.EndPDFContent();

			var documentDirectories = NSSearchPath.GetDirectories(NSSearchPathDirectory.DocumentDirectory, NSSearchPathDomain.User, true);
			var documentDirectory = documentDirectories.ElementAt(0);
			var documentDirectoryFilename = Path.Combine(documentDirectory, "fileName.pdf"); //Not sure about extension 
			NSError error;
			pdfData.Save(documentDirectoryFilename, true, out error);

			var printInfo = UIPrintInfo.PrintInfo;

			printInfo.Duplex = UIPrintInfoDuplex.LongEdge;

			printInfo.OutputType = UIPrintInfoOutputType.General;

			printInfo.JobName = "Invoice";

			var printer = UIPrintInteractionController.SharedPrintController;

			printer.PrintInfo = printInfo;

			printer.PrintingItem = NSData.FromFile(documentDirectoryFilename);

			printer.ShowsPageRange = true;

			printer.Present(true, (handler, completed, err) =>
			{
				if (!completed && err != null)
				{
					Console.WriteLine("Printer Error");
				}
			});


		}
		void PrintingCompleted(UIPrintInteractionController controller, bool completed, NSError error)
		{

		}

	}
}
