// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GreenleafiManager
{
	public partial class CurrentStockReportResultsViewController : UIViewController
	{
		public StockReportModel StockReportModel { get; set; }
		public string Location { get; set;}
		public CurrentStockReportResultsViewController (IntPtr handle) : base (handle)
		{
			
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			if (StockReportModel == null)
			{
					StockReportModel = new StockReportModel();
			}
			ReportDateFilterLabel.Text = "Run on " + DateTime.Now;
			TotalTagPriceLabel.Text = StockReportModel.TotalValueOfItems.ToString("C");
			NumberOfItemsLabel.Text = StockReportModel.TotalOfItems.ToString();
			ReportLocationFilterLabel.Text = Location;
		}
	}
}
